version: 2
defaults:
  workspace_root: &workspace_root
    ~/signupapigouv

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8-stretch

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-signupapigouv-node-{{ checksum "yarn.lock" }}
        - v1-signupapigouv-node-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-signupapigouv-yarn-{{ checksum "yarn.lock" }}
            - v1-signupapigouv-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: v1-signupapigouv-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: v1-signupapigouv-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  test:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn test

  build:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Build output bundles
          command: yarn build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .next/

  export:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Export output bundles
          command: yarn export

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - out/

  deploy:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - add_ssh_keys:
          fingerprints:
            - fc:cd:0a:54:ee:5b:51:49:74:3d:d3:03:41:89:f6:8a

      - run:
          name: Setup SSH to GitHub
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: Set SSH user email
          command: git config --global user.email "contact@api.gouv.fr"

      - run:
          name: Set SSH user name
          command: git config --global user.name "CircleCI"

      - deploy:
          name: Deploy to gh-pages
          command: |
            yarn deploy

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - test:
          requires:
            - install
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - export:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - export
          filters:
            branches:
              only: master
